# Generated by Django 5.0.4 on 2024-04-13 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_name", models.CharField(max_length=255)),
                ("job_description", models.CharField(max_length=255)),
                ("job_status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="System_User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="JobsTaken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_status", models.BooleanField(default=False)),
                (
                    "current_job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="app.joblisting"
                    ),
                ),
                (
                    "job_doer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.system_user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="joblisting",
            name="job_poster",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="app.system_user"
            ),
        ),
    ]
