# Generated by Django 5.0.4 on 2024-04-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_joblisting_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobstaken",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
